<?php
$data = array (
  0 => 
  array (
    'cat_id' => '1',
    'cat_name' => '食品生鲜',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '5',
    'sort_order' => '1',
    'has_children' => '3',
    'goods_num' => 0,
  ),
  1 => 
  array (
    'cat_id' => '2',
    'cat_name' => '服装服饰',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '2',
    'has_children' => '7',
    'goods_num' => 0,
  ),
  2 => 
  array (
    'cat_id' => '3',
    'cat_name' => '个护化妆',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '3',
    'has_children' => '5',
    'goods_num' => 0,
  ),
  3 => 
  array (
    'cat_id' => '4',
    'cat_name' => '手机数码',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '8',
    'sort_order' => '4',
    'has_children' => '3',
    'goods_num' => 0,
  ),
  4 => 
  array (
    'cat_id' => '5',
    'cat_name' => '家用电器',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '5',
    'has_children' => '3',
    'goods_num' => 0,
  ),
  5 => 
  array (
    'cat_id' => '6',
    'cat_name' => '家纺家居',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '6',
    'has_children' => '4',
    'goods_num' => 0,
  ),
  6 => 
  array (
    'cat_id' => '7',
    'cat_name' => '酒类饮料',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '7',
    'has_children' => '2',
    'goods_num' => '2',
  ),
  7 => 
  array (
    'cat_id' => '8',
    'cat_name' => '母婴用品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '8',
    'has_children' => '3',
    'goods_num' => 0,
  ),
  8 => 
  array (
    'cat_id' => '358',
    'cat_name' => '食  品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '9',
    'has_children' => '8',
    'goods_num' => '28',
  ),
  9 => 
  array (
    'cat_id' => '376',
    'cat_name' => '生鲜水果',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '5',
    'goods_num' => 0,
  ),
  10 => 
  array (
    'cat_id' => '372',
    'cat_name' => '饮料酒水',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '7',
    'goods_num' => 0,
  ),
  11 => 
  array (
    'cat_id' => '383',
    'cat_name' => '家居生活',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '9',
    'goods_num' => 0,
  ),
  12 => 
  array (
    'cat_id' => '359',
    'cat_name' => '粮油副食',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '7',
    'goods_num' => 0,
  ),
  13 => 
  array (
    'cat_id' => '390',
    'cat_name' => '美容洗护',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '6',
    'goods_num' => 0,
  ),
  14 => 
  array (
    'cat_id' => '384',
    'cat_name' => '文体玩具',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '5',
    'goods_num' => 0,
  ),
  15 => 
  array (
    'cat_id' => '386',
    'cat_name' => '家用小家电',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
  ),
  16 => 
  array (
    'cat_id' => '499',
    'cat_name' => '家庭清洁',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '8',
    'goods_num' => 0,
  ),
  17 => 
  array (
    'cat_id' => '14',
    'cat_name' => '进口水果',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '10',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  18 => 
  array (
    'cat_id' => '13',
    'cat_name' => '糖果巧克力',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '11',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  19 => 
  array (
    'cat_id' => '9',
    'cat_name' => '牛奶乳品',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '12',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  20 => 
  array (
    'cat_id' => '57',
    'cat_name' => '男装馆',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
  ),
  21 => 
  array (
    'cat_id' => '368',
    'cat_name' => '雪纺衫',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  22 => 
  array (
    'cat_id' => '55',
    'cat_name' => '女装馆',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
  ),
  23 => 
  array (
    'cat_id' => '58',
    'cat_name' => '户外鞋服',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  24 => 
  array (
    'cat_id' => '59',
    'cat_name' => '女鞋馆',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  25 => 
  array (
    'cat_id' => '56',
    'cat_name' => '内衣馆',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
  ),
  26 => 
  array (
    'cat_id' => '60',
    'cat_name' => '箱包馆',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
  ),
  27 => 
  array (
    'cat_id' => '113',
    'cat_name' => '香水彩妆',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '10',
    'has_children' => '3',
    'goods_num' => 0,
  ),
  28 => 
  array (
    'cat_id' => '112',
    'cat_name' => '口腔护理',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  29 => 
  array (
    'cat_id' => '109',
    'cat_name' => '面部护肤',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
  ),
  30 => 
  array (
    'cat_id' => '110',
    'cat_name' => '洗发护发',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
  ),
  31 => 
  array (
    'cat_id' => '111',
    'cat_name' => '身体护肤',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  32 => 
  array (
    'cat_id' => '146',
    'cat_name' => '数码影音',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  33 => 
  array (
    'cat_id' => '144',
    'cat_name' => '热卖手机',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
  ),
  34 => 
  array (
    'cat_id' => '145',
    'cat_name' => '手机配件',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  35 => 
  array (
    'cat_id' => '178',
    'cat_name' => '大家电',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  36 => 
  array (
    'cat_id' => '179',
    'cat_name' => '生活电器',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  37 => 
  array (
    'cat_id' => '180',
    'cat_name' => '厨房电器',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  38 => 
  array (
    'cat_id' => '306',
    'cat_name' => '家纺',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  39 => 
  array (
    'cat_id' => '310',
    'cat_name' => '家装软饰',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  40 => 
  array (
    'cat_id' => '307',
    'cat_name' => '家具',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  41 => 
  array (
    'cat_id' => '308',
    'cat_name' => '厨具',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  42 => 
  array (
    'cat_id' => '272',
    'cat_name' => '冲调饮品',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
  ),
  43 => 
  array (
    'cat_id' => '273',
    'cat_name' => '饮料饮品',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
  ),
  44 => 
  array (
    'cat_id' => '222',
    'cat_name' => '营养/辅食',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  45 => 
  array (
    'cat_id' => '223',
    'cat_name' => '孕婴洗护',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  46 => 
  array (
    'cat_id' => '221',
    'cat_name' => '孕婴奶粉',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  47 => 
  array (
    'cat_id' => '68',
    'cat_name' => '防晒衫',
    'measure_unit' => '',
    'parent_id' => '55',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  48 => 
  array (
    'cat_id' => '61',
    'cat_name' => '连衣裙',
    'measure_unit' => '',
    'parent_id' => '55',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  49 => 
  array (
    'cat_id' => '63',
    'cat_name' => '棉麻T恤',
    'measure_unit' => '',
    'parent_id' => '55',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  50 => 
  array (
    'cat_id' => '74',
    'cat_name' => '夏季睡衣',
    'measure_unit' => '',
    'parent_id' => '56',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  51 => 
  array (
    'cat_id' => '84',
    'cat_name' => 'POLO衫',
    'measure_unit' => '',
    'parent_id' => '57',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  52 => 
  array (
    'cat_id' => '103',
    'cat_name' => '女士钱包',
    'measure_unit' => '',
    'parent_id' => '60',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  53 => 
  array (
    'cat_id' => '106',
    'cat_name' => '旅行箱',
    'measure_unit' => '',
    'parent_id' => '60',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  54 => 
  array (
    'cat_id' => '107',
    'cat_name' => '拉杆箱',
    'measure_unit' => '',
    'parent_id' => '60',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  55 => 
  array (
    'cat_id' => '108',
    'cat_name' => '拉杆包',
    'measure_unit' => '',
    'parent_id' => '60',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  56 => 
  array (
    'cat_id' => '115',
    'cat_name' => '护肤',
    'measure_unit' => '',
    'parent_id' => '109',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  57 => 
  array (
    'cat_id' => '116',
    'cat_name' => '面膜',
    'measure_unit' => '',
    'parent_id' => '109',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  58 => 
  array (
    'cat_id' => '118',
    'cat_name' => '套装',
    'measure_unit' => '',
    'parent_id' => '109',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  59 => 
  array (
    'cat_id' => '114',
    'cat_name' => '清洁',
    'measure_unit' => '',
    'parent_id' => '109',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  60 => 
  array (
    'cat_id' => '124',
    'cat_name' => '套装',
    'measure_unit' => '',
    'parent_id' => '110',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  61 => 
  array (
    'cat_id' => '119',
    'cat_name' => '洗发',
    'measure_unit' => '',
    'parent_id' => '110',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  62 => 
  array (
    'cat_id' => '120',
    'cat_name' => '护发',
    'measure_unit' => '',
    'parent_id' => '110',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  63 => 
  array (
    'cat_id' => '122',
    'cat_name' => '造型',
    'measure_unit' => '',
    'parent_id' => '110',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  64 => 
  array (
    'cat_id' => '143',
    'cat_name' => '套装',
    'measure_unit' => '',
    'parent_id' => '113',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  65 => 
  array (
    'cat_id' => '136',
    'cat_name' => '香水',
    'measure_unit' => '',
    'parent_id' => '113',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  66 => 
  array (
    'cat_id' => '140',
    'cat_name' => '唇部',
    'measure_unit' => '',
    'parent_id' => '113',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  67 => 
  array (
    'cat_id' => '149',
    'cat_name' => 'iPhone',
    'measure_unit' => '',
    'parent_id' => '144',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  68 => 
  array (
    'cat_id' => '150',
    'cat_name' => '小米特供',
    'measure_unit' => '',
    'parent_id' => '144',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  69 => 
  array (
    'cat_id' => '152',
    'cat_name' => '华为荣耀',
    'measure_unit' => '',
    'parent_id' => '144',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  70 => 
  array (
    'cat_id' => '148',
    'cat_name' => '三星盖乐世',
    'measure_unit' => '',
    'parent_id' => '144',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  71 => 
  array (
    'cat_id' => '288',
    'cat_name' => '咖啡',
    'measure_unit' => '',
    'parent_id' => '272',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  72 => 
  array (
    'cat_id' => '285',
    'cat_name' => '茶叶',
    'measure_unit' => '',
    'parent_id' => '272',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  73 => 
  array (
    'cat_id' => '294',
    'cat_name' => '酸奶',
    'measure_unit' => '',
    'parent_id' => '273',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  74 => 
  array (
    'cat_id' => '289',
    'cat_name' => '果蔬汁',
    'measure_unit' => '',
    'parent_id' => '273',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  75 => 
  array (
    'cat_id' => '291',
    'cat_name' => '碳酸饮料',
    'measure_unit' => '',
    'parent_id' => '273',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  76 => 
  array (
    'cat_id' => '365',
    'cat_name' => '散称食品',
    'measure_unit' => '',
    'parent_id' => '358',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
  ),
  77 => 
  array (
    'cat_id' => '362',
    'cat_name' => '冲调保健',
    'measure_unit' => '',
    'parent_id' => '358',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '9',
    'goods_num' => 0,
  ),
  78 => 
  array (
    'cat_id' => '363',
    'cat_name' => '休闲食品',
    'measure_unit' => '',
    'parent_id' => '358',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '8',
    'goods_num' => '2',
  ),
  79 => 
  array (
    'cat_id' => '381',
    'cat_name' => '冷冻食品',
    'measure_unit' => '',
    'parent_id' => '358',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '6',
    'goods_num' => 0,
  ),
  80 => 
  array (
    'cat_id' => '364',
    'cat_name' => '坚果炒货',
    'measure_unit' => '',
    'parent_id' => '358',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  81 => 
  array (
    'cat_id' => '361',
    'cat_name' => '方便速食',
    'measure_unit' => '',
    'parent_id' => '358',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '7',
    'goods_num' => '18',
  ),
  82 => 
  array (
    'cat_id' => '370',
    'cat_name' => '糕点饼干',
    'measure_unit' => '',
    'parent_id' => '358',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '6',
    'goods_num' => '2',
  ),
  83 => 
  array (
    'cat_id' => '374',
    'cat_name' => '地方特产',
    'measure_unit' => '',
    'parent_id' => '358',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
  ),
  84 => 
  array (
    'cat_id' => '397',
    'cat_name' => '散称杂粮',
    'measure_unit' => '',
    'parent_id' => '359',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  85 => 
  array (
    'cat_id' => '509',
    'cat_name' => '菌菇干货',
    'measure_unit' => '',
    'parent_id' => '359',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  86 => 
  array (
    'cat_id' => '395',
    'cat_name' => '食用油',
    'measure_unit' => '',
    'parent_id' => '359',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  87 => 
  array (
    'cat_id' => '510',
    'cat_name' => '下饭菜',
    'measure_unit' => '',
    'parent_id' => '359',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
  ),
  88 => 
  array (
    'cat_id' => '507',
    'cat_name' => '大米面粉',
    'measure_unit' => '',
    'parent_id' => '359',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  89 => 
  array (
    'cat_id' => '511',
    'cat_name' => '调味酱',
    'measure_unit' => '',
    'parent_id' => '359',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  90 => 
  array (
    'cat_id' => '508',
    'cat_name' => '厨房调味',
    'measure_unit' => '',
    'parent_id' => '359',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '7',
    'goods_num' => 0,
  ),
  91 => 
  array (
    'cat_id' => '411',
    'cat_name' => '挂面',
    'measure_unit' => '',
    'parent_id' => '361',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  92 => 
  array (
    'cat_id' => '521',
    'cat_name' => '速食米线/粉',
    'measure_unit' => '',
    'parent_id' => '361',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 3,
  ),
  93 => 
  array (
    'cat_id' => '412',
    'cat_name' => '火腿',
    'measure_unit' => '',
    'parent_id' => '361',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '53',
  ),
  94 => 
  array (
    'cat_id' => '409',
    'cat_name' => '干吃面',
    'measure_unit' => '',
    'parent_id' => '361',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 11,
  ),
  95 => 
  array (
    'cat_id' => '407',
    'cat_name' => '方便面',
    'measure_unit' => '',
    'parent_id' => '361',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 55,
  ),
  96 => 
  array (
    'cat_id' => '410',
    'cat_name' => '八宝粥',
    'measure_unit' => '',
    'parent_id' => '361',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '12',
  ),
  97 => 
  array (
    'cat_id' => '520',
    'cat_name' => '蛋制品',
    'measure_unit' => '',
    'parent_id' => '361',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  98 => 
  array (
    'cat_id' => '414',
    'cat_name' => '麦片谷物',
    'measure_unit' => '',
    'parent_id' => '362',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  99 => 
  array (
    'cat_id' => '421',
    'cat_name' => '豆浆/豆奶粉',
    'measure_unit' => '',
    'parent_id' => '362',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  100 => 
  array (
    'cat_id' => '418',
    'cat_name' => '芝麻糊',
    'measure_unit' => '',
    'parent_id' => '362',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  101 => 
  array (
    'cat_id' => '415',
    'cat_name' => '咖啡',
    'measure_unit' => '',
    'parent_id' => '362',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  102 => 
  array (
    'cat_id' => '419',
    'cat_name' => '健康保健',
    'measure_unit' => '',
    'parent_id' => '362',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  103 => 
  array (
    'cat_id' => '416',
    'cat_name' => '果味冲调',
    'measure_unit' => '',
    'parent_id' => '362',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  104 => 
  array (
    'cat_id' => '413',
    'cat_name' => '奶粉',
    'measure_unit' => '',
    'parent_id' => '362',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  105 => 
  array (
    'cat_id' => '420',
    'cat_name' => '蜂蜜、糖',
    'measure_unit' => '',
    'parent_id' => '362',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  106 => 
  array (
    'cat_id' => '417',
    'cat_name' => '奶茶',
    'measure_unit' => '',
    'parent_id' => '362',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  107 => 
  array (
    'cat_id' => '428',
    'cat_name' => '果冻',
    'measure_unit' => '',
    'parent_id' => '363',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  108 => 
  array (
    'cat_id' => '519',
    'cat_name' => '肉类/豆制品',
    'measure_unit' => '',
    'parent_id' => '363',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  109 => 
  array (
    'cat_id' => '430',
    'cat_name' => '小食品',
    'measure_unit' => '',
    'parent_id' => '363',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  110 => 
  array (
    'cat_id' => '425',
    'cat_name' => '果脯蜜饯',
    'measure_unit' => '',
    'parent_id' => '363',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  111 => 
  array (
    'cat_id' => '422',
    'cat_name' => '膨化食品',
    'measure_unit' => '',
    'parent_id' => '363',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
  ),
  112 => 
  array (
    'cat_id' => '427',
    'cat_name' => '巧克力',
    'measure_unit' => '',
    'parent_id' => '363',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  113 => 
  array (
    'cat_id' => '423',
    'cat_name' => '糖果',
    'measure_unit' => '',
    'parent_id' => '363',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  114 => 
  array (
    'cat_id' => '429',
    'cat_name' => '锅巴',
    'measure_unit' => '',
    'parent_id' => '363',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  115 => 
  array (
    'cat_id' => '433',
    'cat_name' => '散饼干',
    'measure_unit' => '',
    'parent_id' => '365',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  116 => 
  array (
    'cat_id' => '436',
    'cat_name' => '散称果冻',
    'measure_unit' => '',
    'parent_id' => '365',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  117 => 
  array (
    'cat_id' => '434',
    'cat_name' => '散称糖果',
    'measure_unit' => '',
    'parent_id' => '365',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  118 => 
  array (
    'cat_id' => '435',
    'cat_name' => '散称糕点',
    'measure_unit' => '',
    'parent_id' => '365',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  119 => 
  array (
    'cat_id' => '523',
    'cat_name' => '曲奇',
    'measure_unit' => '',
    'parent_id' => '370',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  120 => 
  array (
    'cat_id' => '439',
    'cat_name' => '饼干',
    'measure_unit' => '',
    'parent_id' => '370',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 57,
  ),
  121 => 
  array (
    'cat_id' => '443',
    'cat_name' => '糕点',
    'measure_unit' => '',
    'parent_id' => '370',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  122 => 
  array (
    'cat_id' => '442',
    'cat_name' => '蛋卷',
    'measure_unit' => '',
    'parent_id' => '370',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '12',
  ),
  123 => 
  array (
    'cat_id' => '522',
    'cat_name' => '面包',
    'measure_unit' => '',
    'parent_id' => '370',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 43,
  ),
  124 => 
  array (
    'cat_id' => '440',
    'cat_name' => '派',
    'measure_unit' => '',
    'parent_id' => '370',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 9,
  ),
  125 => 
  array (
    'cat_id' => '447',
    'cat_name' => '预调酒',
    'measure_unit' => '',
    'parent_id' => '371',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  126 => 
  array (
    'cat_id' => '448',
    'cat_name' => '保健酒',
    'measure_unit' => '',
    'parent_id' => '371',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  127 => 
  array (
    'cat_id' => '446',
    'cat_name' => '红酒',
    'measure_unit' => '',
    'parent_id' => '371',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  128 => 
  array (
    'cat_id' => '445',
    'cat_name' => '白酒',
    'measure_unit' => '',
    'parent_id' => '371',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  129 => 
  array (
    'cat_id' => '444',
    'cat_name' => '啤酒',
    'measure_unit' => '',
    'parent_id' => '371',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  130 => 
  array (
    'cat_id' => '453',
    'cat_name' => '水',
    'measure_unit' => '',
    'parent_id' => '372',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  131 => 
  array (
    'cat_id' => '449',
    'cat_name' => '碳酸饮料',
    'measure_unit' => '',
    'parent_id' => '372',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 4,
  ),
  132 => 
  array (
    'cat_id' => '371',
    'cat_name' => '酒类',
    'measure_unit' => '',
    'parent_id' => '372',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '5',
    'goods_num' => 0,
  ),
  133 => 
  array (
    'cat_id' => '452',
    'cat_name' => '功能饮料',
    'measure_unit' => '',
    'parent_id' => '372',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  134 => 
  array (
    'cat_id' => '450',
    'cat_name' => '茶饮品',
    'measure_unit' => '',
    'parent_id' => '372',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  135 => 
  array (
    'cat_id' => '373',
    'cat_name' => '牛奶乳饮品',
    'measure_unit' => '',
    'parent_id' => '372',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '5',
    'goods_num' => 0,
  ),
  136 => 
  array (
    'cat_id' => '451',
    'cat_name' => '果汁饮品',
    'measure_unit' => '',
    'parent_id' => '372',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
  ),
  137 => 
  array (
    'cat_id' => '457',
    'cat_name' => '常温奶',
    'measure_unit' => '',
    'parent_id' => '373',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  138 => 
  array (
    'cat_id' => '454',
    'cat_name' => '乳饮品',
    'measure_unit' => '',
    'parent_id' => '373',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  139 => 
  array (
    'cat_id' => '458',
    'cat_name' => '儿童奶',
    'measure_unit' => '',
    'parent_id' => '373',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  140 => 
  array (
    'cat_id' => '455',
    'cat_name' => '果味奶饮品',
    'measure_unit' => '',
    'parent_id' => '373',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  141 => 
  array (
    'cat_id' => '456',
    'cat_name' => '酸奶',
    'measure_unit' => '',
    'parent_id' => '373',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '5',
  ),
  142 => 
  array (
    'cat_id' => '459',
    'cat_name' => '碗团',
    'measure_unit' => '',
    'parent_id' => '374',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  143 => 
  array (
    'cat_id' => '462',
    'cat_name' => '芝麻饼',
    'measure_unit' => '',
    'parent_id' => '374',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  144 => 
  array (
    'cat_id' => '460',
    'cat_name' => '枣',
    'measure_unit' => '',
    'parent_id' => '374',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  145 => 
  array (
    'cat_id' => '378',
    'cat_name' => '生肉',
    'measure_unit' => '',
    'parent_id' => '376',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  146 => 
  array (
    'cat_id' => '380',
    'cat_name' => '散称熟食',
    'measure_unit' => '',
    'parent_id' => '376',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  147 => 
  array (
    'cat_id' => '498',
    'cat_name' => '蔬菜',
    'measure_unit' => '',
    'parent_id' => '376',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  148 => 
  array (
    'cat_id' => '379',
    'cat_name' => '水产',
    'measure_unit' => '',
    'parent_id' => '376',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  149 => 
  array (
    'cat_id' => '377',
    'cat_name' => '水果',
    'measure_unit' => '',
    'parent_id' => '376',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  150 => 
  array (
    'cat_id' => '530',
    'cat_name' => '冷冻肉产品',
    'measure_unit' => '',
    'parent_id' => '381',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  151 => 
  array (
    'cat_id' => '527',
    'cat_name' => '汤圆',
    'measure_unit' => '',
    'parent_id' => '381',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  152 => 
  array (
    'cat_id' => '531',
    'cat_name' => '面点',
    'measure_unit' => '',
    'parent_id' => '381',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  153 => 
  array (
    'cat_id' => '528',
    'cat_name' => '火锅丸',
    'measure_unit' => '',
    'parent_id' => '381',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  154 => 
  array (
    'cat_id' => '529',
    'cat_name' => '冷冻水产品',
    'measure_unit' => '',
    'parent_id' => '381',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  155 => 
  array (
    'cat_id' => '526',
    'cat_name' => '饺子',
    'measure_unit' => '',
    'parent_id' => '381',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  156 => 
  array (
    'cat_id' => '385',
    'cat_name' => '厨房用具',
    'measure_unit' => '',
    'parent_id' => '383',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '7',
    'goods_num' => 0,
  ),
  157 => 
  array (
    'cat_id' => '514',
    'cat_name' => '卫浴用品',
    'measure_unit' => '',
    'parent_id' => '383',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  158 => 
  array (
    'cat_id' => '388',
    'cat_name' => '床上用品',
    'measure_unit' => '',
    'parent_id' => '383',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '6',
    'goods_num' => 0,
  ),
  159 => 
  array (
    'cat_id' => '518',
    'cat_name' => '日用洗晒',
    'measure_unit' => '',
    'parent_id' => '383',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  160 => 
  array (
    'cat_id' => '515',
    'cat_name' => '一次性用品',
    'measure_unit' => '',
    'parent_id' => '383',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  161 => 
  array (
    'cat_id' => '394',
    'cat_name' => '年货节庆',
    'measure_unit' => '',
    'parent_id' => '383',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  162 => 
  array (
    'cat_id' => '389',
    'cat_name' => '针织家居',
    'measure_unit' => '',
    'parent_id' => '383',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '6',
    'goods_num' => 0,
  ),
  163 => 
  array (
    'cat_id' => '517',
    'cat_name' => '箱包饰品',
    'measure_unit' => '',
    'parent_id' => '383',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  164 => 
  array (
    'cat_id' => '516',
    'cat_name' => '整理收纳',
    'measure_unit' => '',
    'parent_id' => '383',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  165 => 
  array (
    'cat_id' => '464',
    'cat_name' => '办公用品',
    'measure_unit' => '',
    'parent_id' => '384',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  166 => 
  array (
    'cat_id' => '466',
    'cat_name' => '礼品',
    'measure_unit' => '',
    'parent_id' => '384',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  167 => 
  array (
    'cat_id' => '467',
    'cat_name' => '棋牌扑克',
    'measure_unit' => '',
    'parent_id' => '384',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  168 => 
  array (
    'cat_id' => '465',
    'cat_name' => '玩具',
    'measure_unit' => '',
    'parent_id' => '384',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  169 => 
  array (
    'cat_id' => '463',
    'cat_name' => '体育用品',
    'measure_unit' => '',
    'parent_id' => '384',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  170 => 
  array (
    'cat_id' => '472',
    'cat_name' => '清洁用品',
    'measure_unit' => '',
    'parent_id' => '385',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  171 => 
  array (
    'cat_id' => '469',
    'cat_name' => '陶瓷类',
    'measure_unit' => '',
    'parent_id' => '385',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  172 => 
  array (
    'cat_id' => '473',
    'cat_name' => '刀具',
    'measure_unit' => '',
    'parent_id' => '385',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  173 => 
  array (
    'cat_id' => '470',
    'cat_name' => '塑料制品',
    'measure_unit' => '',
    'parent_id' => '385',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  174 => 
  array (
    'cat_id' => '474',
    'cat_name' => '厨房电器',
    'measure_unit' => '',
    'parent_id' => '385',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  175 => 
  array (
    'cat_id' => '471',
    'cat_name' => '餐具',
    'measure_unit' => '',
    'parent_id' => '385',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  176 => 
  array (
    'cat_id' => '468',
    'cat_name' => '不锈钢厨具',
    'measure_unit' => '',
    'parent_id' => '385',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  177 => 
  array (
    'cat_id' => '476',
    'cat_name' => '小家电',
    'measure_unit' => '',
    'parent_id' => '386',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  178 => 
  array (
    'cat_id' => '475',
    'cat_name' => '插座',
    'measure_unit' => '',
    'parent_id' => '386',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  179 => 
  array (
    'cat_id' => '479',
    'cat_name' => '床垫/床褥',
    'measure_unit' => '',
    'parent_id' => '388',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  180 => 
  array (
    'cat_id' => '480',
    'cat_name' => '床品套装',
    'measure_unit' => '',
    'parent_id' => '388',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  181 => 
  array (
    'cat_id' => '477',
    'cat_name' => '被子/枕头',
    'measure_unit' => '',
    'parent_id' => '388',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  182 => 
  array (
    'cat_id' => '482',
    'cat_name' => '蚊帐/凉席',
    'measure_unit' => '',
    'parent_id' => '388',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  183 => 
  array (
    'cat_id' => '478',
    'cat_name' => '床单被罩',
    'measure_unit' => '',
    'parent_id' => '388',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  184 => 
  array (
    'cat_id' => '481',
    'cat_name' => '窗帘/窗纱',
    'measure_unit' => '',
    'parent_id' => '388',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  185 => 
  array (
    'cat_id' => '487',
    'cat_name' => '洗浴用品',
    'measure_unit' => '',
    'parent_id' => '389',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  186 => 
  array (
    'cat_id' => '485',
    'cat_name' => '睡衣',
    'measure_unit' => '',
    'parent_id' => '389',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  187 => 
  array (
    'cat_id' => '486',
    'cat_name' => '毛巾/浴巾',
    'measure_unit' => '',
    'parent_id' => '389',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  188 => 
  array (
    'cat_id' => '483',
    'cat_name' => '袜子',
    'measure_unit' => '',
    'parent_id' => '389',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  189 => 
  array (
    'cat_id' => '536',
    'cat_name' => '拖鞋',
    'measure_unit' => '',
    'parent_id' => '389',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
  ),
  190 => 
  array (
    'cat_id' => '484',
    'cat_name' => '内衣',
    'measure_unit' => '',
    'parent_id' => '389',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  191 => 
  array (
    'cat_id' => '491',
    'cat_name' => '口腔护理',
    'measure_unit' => '',
    'parent_id' => '390',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
  ),
  192 => 
  array (
    'cat_id' => '513',
    'cat_name' => '男性护理',
    'measure_unit' => '',
    'parent_id' => '390',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  193 => 
  array (
    'cat_id' => '512',
    'cat_name' => '精致彩妆',
    'measure_unit' => '',
    'parent_id' => '390',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  194 => 
  array (
    'cat_id' => '490',
    'cat_name' => '护肤品',
    'measure_unit' => '',
    'parent_id' => '390',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  195 => 
  array (
    'cat_id' => '493',
    'cat_name' => '女性护理',
    'measure_unit' => '',
    'parent_id' => '390',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '5',
  ),
  196 => 
  array (
    'cat_id' => '488',
    'cat_name' => '个人洗护',
    'measure_unit' => '',
    'parent_id' => '390',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  197 => 
  array (
    'cat_id' => '504',
    'cat_name' => '驱蚊驱虫',
    'measure_unit' => '',
    'parent_id' => '499',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  198 => 
  array (
    'cat_id' => '502',
    'cat_name' => '卫生间清洁',
    'measure_unit' => '',
    'parent_id' => '499',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  199 => 
  array (
    'cat_id' => '503',
    'cat_name' => '清洁工具',
    'measure_unit' => '',
    'parent_id' => '499',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  200 => 
  array (
    'cat_id' => '505',
    'cat_name' => '家私清洁',
    'measure_unit' => '',
    'parent_id' => '499',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  201 => 
  array (
    'cat_id' => '501',
    'cat_name' => '厨房清洁',
    'measure_unit' => '',
    'parent_id' => '499',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  202 => 
  array (
    'cat_id' => '506',
    'cat_name' => '客厅清洁',
    'measure_unit' => '',
    'parent_id' => '499',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  203 => 
  array (
    'cat_id' => '500',
    'cat_name' => '衣物清洁',
    'measure_unit' => '',
    'parent_id' => '499',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
  ),
  204 => 
  array (
    'cat_id' => '391',
    'cat_name' => '纸制品',
    'measure_unit' => '',
    'parent_id' => '499',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
  ),
  205 => 
  array (
    'cat_id' => '533',
    'cat_name' => '糖',
    'measure_unit' => '',
    'parent_id' => '508',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  206 => 
  array (
    'cat_id' => '534',
    'cat_name' => '芝麻油',
    'measure_unit' => '',
    'parent_id' => '508',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  207 => 
  array (
    'cat_id' => '404',
    'cat_name' => '香料',
    'measure_unit' => '',
    'parent_id' => '508',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  208 => 
  array (
    'cat_id' => '399',
    'cat_name' => '醋',
    'measure_unit' => '',
    'parent_id' => '508',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  209 => 
  array (
    'cat_id' => '535',
    'cat_name' => '料酒',
    'measure_unit' => '',
    'parent_id' => '508',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  210 => 
  array (
    'cat_id' => '403',
    'cat_name' => '调味料',
    'measure_unit' => '',
    'parent_id' => '508',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  211 => 
  array (
    'cat_id' => '532',
    'cat_name' => '酱油',
    'measure_unit' => '',
    'parent_id' => '508',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  212 => 
  array (
    'cat_id' => '437',
    'cat_name' => '酱菜',
    'measure_unit' => '',
    'parent_id' => '510',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
);
?>