<?php
$data = array (
  1 => 
  array (
    'cat_id' => '1',
    'cat_name' => '食品生鲜',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '5',
    'sort_order' => '1',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 0,
    'id' => '1',
    'name' => '食品生鲜',
  ),
  14 => 
  array (
    'cat_id' => '14',
    'cat_name' => '进口水果',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '10',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '14',
    'name' => '进口水果',
  ),
  13 => 
  array (
    'cat_id' => '13',
    'cat_name' => '糖果巧克力',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '11',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '13',
    'name' => '糖果巧克力',
  ),
  9 => 
  array (
    'cat_id' => '9',
    'cat_name' => '牛奶乳品',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '12',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '9',
    'name' => '牛奶乳品',
  ),
  2 => 
  array (
    'cat_id' => '2',
    'cat_name' => '服装服饰',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '2',
    'has_children' => '7',
    'goods_num' => 0,
    'level' => 0,
    'id' => '2',
    'name' => '服装服饰',
  ),
  57 => 
  array (
    'cat_id' => '57',
    'cat_name' => '男装馆',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 1,
    'id' => '57',
    'name' => '男装馆',
  ),
  84 => 
  array (
    'cat_id' => '84',
    'cat_name' => 'POLO衫',
    'measure_unit' => '',
    'parent_id' => '57',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '84',
    'name' => 'POLO衫',
  ),
  368 => 
  array (
    'cat_id' => '368',
    'cat_name' => '雪纺衫',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '368',
    'name' => '雪纺衫',
  ),
  55 => 
  array (
    'cat_id' => '55',
    'cat_name' => '女装馆',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 1,
    'id' => '55',
    'name' => '女装馆',
  ),
  68 => 
  array (
    'cat_id' => '68',
    'cat_name' => '防晒衫',
    'measure_unit' => '',
    'parent_id' => '55',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '68',
    'name' => '防晒衫',
  ),
  61 => 
  array (
    'cat_id' => '61',
    'cat_name' => '连衣裙',
    'measure_unit' => '',
    'parent_id' => '55',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '61',
    'name' => '连衣裙',
  ),
  63 => 
  array (
    'cat_id' => '63',
    'cat_name' => '棉麻T恤',
    'measure_unit' => '',
    'parent_id' => '55',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '63',
    'name' => '棉麻T恤',
  ),
  58 => 
  array (
    'cat_id' => '58',
    'cat_name' => '户外鞋服',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '58',
    'name' => '户外鞋服',
  ),
  59 => 
  array (
    'cat_id' => '59',
    'cat_name' => '女鞋馆',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '59',
    'name' => '女鞋馆',
  ),
  56 => 
  array (
    'cat_id' => '56',
    'cat_name' => '内衣馆',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 1,
    'id' => '56',
    'name' => '内衣馆',
  ),
  74 => 
  array (
    'cat_id' => '74',
    'cat_name' => '夏季睡衣',
    'measure_unit' => '',
    'parent_id' => '56',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '74',
    'name' => '夏季睡衣',
  ),
  60 => 
  array (
    'cat_id' => '60',
    'cat_name' => '箱包馆',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 1,
    'id' => '60',
    'name' => '箱包馆',
  ),
  103 => 
  array (
    'cat_id' => '103',
    'cat_name' => '女士钱包',
    'measure_unit' => '',
    'parent_id' => '60',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '103',
    'name' => '女士钱包',
  ),
  106 => 
  array (
    'cat_id' => '106',
    'cat_name' => '旅行箱',
    'measure_unit' => '',
    'parent_id' => '60',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '106',
    'name' => '旅行箱',
  ),
  107 => 
  array (
    'cat_id' => '107',
    'cat_name' => '拉杆箱',
    'measure_unit' => '',
    'parent_id' => '60',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '107',
    'name' => '拉杆箱',
  ),
  108 => 
  array (
    'cat_id' => '108',
    'cat_name' => '拉杆包',
    'measure_unit' => '',
    'parent_id' => '60',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '108',
    'name' => '拉杆包',
  ),
  3 => 
  array (
    'cat_id' => '3',
    'cat_name' => '个护化妆',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '3',
    'has_children' => '5',
    'goods_num' => 0,
    'level' => 0,
    'id' => '3',
    'name' => '个护化妆',
  ),
  113 => 
  array (
    'cat_id' => '113',
    'cat_name' => '香水彩妆',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '10',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 1,
    'id' => '113',
    'name' => '香水彩妆',
  ),
  143 => 
  array (
    'cat_id' => '143',
    'cat_name' => '套装',
    'measure_unit' => '',
    'parent_id' => '113',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '143',
    'name' => '套装',
  ),
  136 => 
  array (
    'cat_id' => '136',
    'cat_name' => '香水',
    'measure_unit' => '',
    'parent_id' => '113',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '136',
    'name' => '香水',
  ),
  140 => 
  array (
    'cat_id' => '140',
    'cat_name' => '唇部',
    'measure_unit' => '',
    'parent_id' => '113',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '140',
    'name' => '唇部',
  ),
  112 => 
  array (
    'cat_id' => '112',
    'cat_name' => '口腔护理',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '112',
    'name' => '口腔护理',
  ),
  109 => 
  array (
    'cat_id' => '109',
    'cat_name' => '面部护肤',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 1,
    'id' => '109',
    'name' => '面部护肤',
  ),
  115 => 
  array (
    'cat_id' => '115',
    'cat_name' => '护肤',
    'measure_unit' => '',
    'parent_id' => '109',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '115',
    'name' => '护肤',
  ),
  116 => 
  array (
    'cat_id' => '116',
    'cat_name' => '面膜',
    'measure_unit' => '',
    'parent_id' => '109',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '116',
    'name' => '面膜',
  ),
  118 => 
  array (
    'cat_id' => '118',
    'cat_name' => '套装',
    'measure_unit' => '',
    'parent_id' => '109',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '118',
    'name' => '套装',
  ),
  114 => 
  array (
    'cat_id' => '114',
    'cat_name' => '清洁',
    'measure_unit' => '',
    'parent_id' => '109',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '114',
    'name' => '清洁',
  ),
  110 => 
  array (
    'cat_id' => '110',
    'cat_name' => '洗发护发',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 1,
    'id' => '110',
    'name' => '洗发护发',
  ),
  124 => 
  array (
    'cat_id' => '124',
    'cat_name' => '套装',
    'measure_unit' => '',
    'parent_id' => '110',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '124',
    'name' => '套装',
  ),
  119 => 
  array (
    'cat_id' => '119',
    'cat_name' => '洗发',
    'measure_unit' => '',
    'parent_id' => '110',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '119',
    'name' => '洗发',
  ),
  120 => 
  array (
    'cat_id' => '120',
    'cat_name' => '护发',
    'measure_unit' => '',
    'parent_id' => '110',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '120',
    'name' => '护发',
  ),
  122 => 
  array (
    'cat_id' => '122',
    'cat_name' => '造型',
    'measure_unit' => '',
    'parent_id' => '110',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '122',
    'name' => '造型',
  ),
  111 => 
  array (
    'cat_id' => '111',
    'cat_name' => '身体护肤',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '111',
    'name' => '身体护肤',
  ),
  4 => 
  array (
    'cat_id' => '4',
    'cat_name' => '手机数码',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '8',
    'sort_order' => '4',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 0,
    'id' => '4',
    'name' => '手机数码',
  ),
  146 => 
  array (
    'cat_id' => '146',
    'cat_name' => '数码影音',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '146',
    'name' => '数码影音',
  ),
  144 => 
  array (
    'cat_id' => '144',
    'cat_name' => '热卖手机',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 1,
    'id' => '144',
    'name' => '热卖手机',
  ),
  149 => 
  array (
    'cat_id' => '149',
    'cat_name' => 'iPhone',
    'measure_unit' => '',
    'parent_id' => '144',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '149',
    'name' => 'iPhone',
  ),
  150 => 
  array (
    'cat_id' => '150',
    'cat_name' => '小米特供',
    'measure_unit' => '',
    'parent_id' => '144',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '150',
    'name' => '小米特供',
  ),
  152 => 
  array (
    'cat_id' => '152',
    'cat_name' => '华为荣耀',
    'measure_unit' => '',
    'parent_id' => '144',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '152',
    'name' => '华为荣耀',
  ),
  148 => 
  array (
    'cat_id' => '148',
    'cat_name' => '三星盖乐世',
    'measure_unit' => '',
    'parent_id' => '144',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '148',
    'name' => '三星盖乐世',
  ),
  145 => 
  array (
    'cat_id' => '145',
    'cat_name' => '手机配件',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '145',
    'name' => '手机配件',
  ),
  5 => 
  array (
    'cat_id' => '5',
    'cat_name' => '家用电器',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '5',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 0,
    'id' => '5',
    'name' => '家用电器',
  ),
  178 => 
  array (
    'cat_id' => '178',
    'cat_name' => '大家电',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '178',
    'name' => '大家电',
  ),
  179 => 
  array (
    'cat_id' => '179',
    'cat_name' => '生活电器',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '179',
    'name' => '生活电器',
  ),
  180 => 
  array (
    'cat_id' => '180',
    'cat_name' => '厨房电器',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '180',
    'name' => '厨房电器',
  ),
  6 => 
  array (
    'cat_id' => '6',
    'cat_name' => '家纺家居',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '6',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 0,
    'id' => '6',
    'name' => '家纺家居',
  ),
  306 => 
  array (
    'cat_id' => '306',
    'cat_name' => '家纺',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '306',
    'name' => '家纺',
  ),
  310 => 
  array (
    'cat_id' => '310',
    'cat_name' => '家装软饰',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '310',
    'name' => '家装软饰',
  ),
  307 => 
  array (
    'cat_id' => '307',
    'cat_name' => '家具',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '307',
    'name' => '家具',
  ),
  308 => 
  array (
    'cat_id' => '308',
    'cat_name' => '厨具',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '308',
    'name' => '厨具',
  ),
  7 => 
  array (
    'cat_id' => '7',
    'cat_name' => '酒类饮料',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '7',
    'has_children' => '2',
    'goods_num' => '2',
    'level' => 0,
    'id' => '7',
    'name' => '酒类饮料',
  ),
  272 => 
  array (
    'cat_id' => '272',
    'cat_name' => '冲调饮品',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 1,
    'id' => '272',
    'name' => '冲调饮品',
  ),
  288 => 
  array (
    'cat_id' => '288',
    'cat_name' => '咖啡',
    'measure_unit' => '',
    'parent_id' => '272',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '288',
    'name' => '咖啡',
  ),
  285 => 
  array (
    'cat_id' => '285',
    'cat_name' => '茶叶',
    'measure_unit' => '',
    'parent_id' => '272',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '285',
    'name' => '茶叶',
  ),
  273 => 
  array (
    'cat_id' => '273',
    'cat_name' => '饮料饮品',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 1,
    'id' => '273',
    'name' => '饮料饮品',
  ),
  294 => 
  array (
    'cat_id' => '294',
    'cat_name' => '酸奶',
    'measure_unit' => '',
    'parent_id' => '273',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '294',
    'name' => '酸奶',
  ),
  289 => 
  array (
    'cat_id' => '289',
    'cat_name' => '果蔬汁',
    'measure_unit' => '',
    'parent_id' => '273',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '289',
    'name' => '果蔬汁',
  ),
  291 => 
  array (
    'cat_id' => '291',
    'cat_name' => '碳酸饮料',
    'measure_unit' => '',
    'parent_id' => '273',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '291',
    'name' => '碳酸饮料',
  ),
  8 => 
  array (
    'cat_id' => '8',
    'cat_name' => '母婴用品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '8',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 0,
    'id' => '8',
    'name' => '母婴用品',
  ),
  222 => 
  array (
    'cat_id' => '222',
    'cat_name' => '营养/辅食',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '222',
    'name' => '营养/辅食',
  ),
  223 => 
  array (
    'cat_id' => '223',
    'cat_name' => '孕婴洗护',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '223',
    'name' => '孕婴洗护',
  ),
  221 => 
  array (
    'cat_id' => '221',
    'cat_name' => '孕婴奶粉',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '221',
    'name' => '孕婴奶粉',
  ),
  358 => 
  array (
    'cat_id' => '358',
    'cat_name' => '食  品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '9',
    'has_children' => '8',
    'goods_num' => '28',
    'level' => 0,
    'id' => '358',
    'name' => '食  品',
  ),
  365 => 
  array (
    'cat_id' => '365',
    'cat_name' => '散称食品',
    'measure_unit' => '',
    'parent_id' => '358',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 1,
    'id' => '365',
    'name' => '散称食品',
  ),
  433 => 
  array (
    'cat_id' => '433',
    'cat_name' => '散饼干',
    'measure_unit' => '',
    'parent_id' => '365',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '433',
    'name' => '散饼干',
  ),
  436 => 
  array (
    'cat_id' => '436',
    'cat_name' => '散称果冻',
    'measure_unit' => '',
    'parent_id' => '365',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '436',
    'name' => '散称果冻',
  ),
  434 => 
  array (
    'cat_id' => '434',
    'cat_name' => '散称糖果',
    'measure_unit' => '',
    'parent_id' => '365',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '434',
    'name' => '散称糖果',
  ),
  435 => 
  array (
    'cat_id' => '435',
    'cat_name' => '散称糕点',
    'measure_unit' => '',
    'parent_id' => '365',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '435',
    'name' => '散称糕点',
  ),
  362 => 
  array (
    'cat_id' => '362',
    'cat_name' => '冲调保健',
    'measure_unit' => '',
    'parent_id' => '358',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '9',
    'goods_num' => 0,
    'level' => 1,
    'id' => '362',
    'name' => '冲调保健',
  ),
  414 => 
  array (
    'cat_id' => '414',
    'cat_name' => '麦片谷物',
    'measure_unit' => '',
    'parent_id' => '362',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '414',
    'name' => '麦片谷物',
  ),
  421 => 
  array (
    'cat_id' => '421',
    'cat_name' => '豆浆/豆奶粉',
    'measure_unit' => '',
    'parent_id' => '362',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '421',
    'name' => '豆浆/豆奶粉',
  ),
  418 => 
  array (
    'cat_id' => '418',
    'cat_name' => '芝麻糊',
    'measure_unit' => '',
    'parent_id' => '362',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '418',
    'name' => '芝麻糊',
  ),
  415 => 
  array (
    'cat_id' => '415',
    'cat_name' => '咖啡',
    'measure_unit' => '',
    'parent_id' => '362',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '415',
    'name' => '咖啡',
  ),
  419 => 
  array (
    'cat_id' => '419',
    'cat_name' => '健康保健',
    'measure_unit' => '',
    'parent_id' => '362',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '419',
    'name' => '健康保健',
  ),
  416 => 
  array (
    'cat_id' => '416',
    'cat_name' => '果味冲调',
    'measure_unit' => '',
    'parent_id' => '362',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '416',
    'name' => '果味冲调',
  ),
  413 => 
  array (
    'cat_id' => '413',
    'cat_name' => '奶粉',
    'measure_unit' => '',
    'parent_id' => '362',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '413',
    'name' => '奶粉',
  ),
  420 => 
  array (
    'cat_id' => '420',
    'cat_name' => '蜂蜜、糖',
    'measure_unit' => '',
    'parent_id' => '362',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '420',
    'name' => '蜂蜜、糖',
  ),
  417 => 
  array (
    'cat_id' => '417',
    'cat_name' => '奶茶',
    'measure_unit' => '',
    'parent_id' => '362',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '417',
    'name' => '奶茶',
  ),
  363 => 
  array (
    'cat_id' => '363',
    'cat_name' => '休闲食品',
    'measure_unit' => '',
    'parent_id' => '358',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '8',
    'goods_num' => '2',
    'level' => 1,
    'id' => '363',
    'name' => '休闲食品',
  ),
  428 => 
  array (
    'cat_id' => '428',
    'cat_name' => '果冻',
    'measure_unit' => '',
    'parent_id' => '363',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '428',
    'name' => '果冻',
  ),
  519 => 
  array (
    'cat_id' => '519',
    'cat_name' => '肉类/豆制品',
    'measure_unit' => '',
    'parent_id' => '363',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '519',
    'name' => '肉类/豆制品',
  ),
  430 => 
  array (
    'cat_id' => '430',
    'cat_name' => '小食品',
    'measure_unit' => '',
    'parent_id' => '363',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '430',
    'name' => '小食品',
  ),
  425 => 
  array (
    'cat_id' => '425',
    'cat_name' => '果脯蜜饯',
    'measure_unit' => '',
    'parent_id' => '363',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '425',
    'name' => '果脯蜜饯',
  ),
  422 => 
  array (
    'cat_id' => '422',
    'cat_name' => '膨化食品',
    'measure_unit' => '',
    'parent_id' => '363',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
    'level' => 2,
    'id' => '422',
    'name' => '膨化食品',
  ),
  427 => 
  array (
    'cat_id' => '427',
    'cat_name' => '巧克力',
    'measure_unit' => '',
    'parent_id' => '363',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '427',
    'name' => '巧克力',
  ),
  423 => 
  array (
    'cat_id' => '423',
    'cat_name' => '糖果',
    'measure_unit' => '',
    'parent_id' => '363',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '423',
    'name' => '糖果',
  ),
  429 => 
  array (
    'cat_id' => '429',
    'cat_name' => '锅巴',
    'measure_unit' => '',
    'parent_id' => '363',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '429',
    'name' => '锅巴',
  ),
  381 => 
  array (
    'cat_id' => '381',
    'cat_name' => '冷冻食品',
    'measure_unit' => '',
    'parent_id' => '358',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '6',
    'goods_num' => 0,
    'level' => 1,
    'id' => '381',
    'name' => '冷冻食品',
  ),
  530 => 
  array (
    'cat_id' => '530',
    'cat_name' => '冷冻肉产品',
    'measure_unit' => '',
    'parent_id' => '381',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '530',
    'name' => '冷冻肉产品',
  ),
  527 => 
  array (
    'cat_id' => '527',
    'cat_name' => '汤圆',
    'measure_unit' => '',
    'parent_id' => '381',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '527',
    'name' => '汤圆',
  ),
  531 => 
  array (
    'cat_id' => '531',
    'cat_name' => '面点',
    'measure_unit' => '',
    'parent_id' => '381',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '531',
    'name' => '面点',
  ),
  528 => 
  array (
    'cat_id' => '528',
    'cat_name' => '火锅丸',
    'measure_unit' => '',
    'parent_id' => '381',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '528',
    'name' => '火锅丸',
  ),
  529 => 
  array (
    'cat_id' => '529',
    'cat_name' => '冷冻水产品',
    'measure_unit' => '',
    'parent_id' => '381',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '529',
    'name' => '冷冻水产品',
  ),
  526 => 
  array (
    'cat_id' => '526',
    'cat_name' => '饺子',
    'measure_unit' => '',
    'parent_id' => '381',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '526',
    'name' => '饺子',
  ),
  364 => 
  array (
    'cat_id' => '364',
    'cat_name' => '坚果炒货',
    'measure_unit' => '',
    'parent_id' => '358',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '364',
    'name' => '坚果炒货',
  ),
  361 => 
  array (
    'cat_id' => '361',
    'cat_name' => '方便速食',
    'measure_unit' => '',
    'parent_id' => '358',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '7',
    'goods_num' => '18',
    'level' => 1,
    'id' => '361',
    'name' => '方便速食',
  ),
  411 => 
  array (
    'cat_id' => '411',
    'cat_name' => '挂面',
    'measure_unit' => '',
    'parent_id' => '361',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '411',
    'name' => '挂面',
  ),
  521 => 
  array (
    'cat_id' => '521',
    'cat_name' => '速食米线/粉',
    'measure_unit' => '',
    'parent_id' => '361',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 3,
    'level' => 2,
    'id' => '521',
    'name' => '速食米线/粉',
  ),
  412 => 
  array (
    'cat_id' => '412',
    'cat_name' => '火腿',
    'measure_unit' => '',
    'parent_id' => '361',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '53',
    'level' => 2,
    'id' => '412',
    'name' => '火腿',
  ),
  409 => 
  array (
    'cat_id' => '409',
    'cat_name' => '干吃面',
    'measure_unit' => '',
    'parent_id' => '361',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 11,
    'level' => 2,
    'id' => '409',
    'name' => '干吃面',
  ),
  407 => 
  array (
    'cat_id' => '407',
    'cat_name' => '方便面',
    'measure_unit' => '',
    'parent_id' => '361',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 55,
    'level' => 2,
    'id' => '407',
    'name' => '方便面',
  ),
  410 => 
  array (
    'cat_id' => '410',
    'cat_name' => '八宝粥',
    'measure_unit' => '',
    'parent_id' => '361',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '12',
    'level' => 2,
    'id' => '410',
    'name' => '八宝粥',
  ),
  520 => 
  array (
    'cat_id' => '520',
    'cat_name' => '蛋制品',
    'measure_unit' => '',
    'parent_id' => '361',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '520',
    'name' => '蛋制品',
  ),
  370 => 
  array (
    'cat_id' => '370',
    'cat_name' => '糕点饼干',
    'measure_unit' => '',
    'parent_id' => '358',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '6',
    'goods_num' => '2',
    'level' => 1,
    'id' => '370',
    'name' => '糕点饼干',
  ),
  523 => 
  array (
    'cat_id' => '523',
    'cat_name' => '曲奇',
    'measure_unit' => '',
    'parent_id' => '370',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '523',
    'name' => '曲奇',
  ),
  439 => 
  array (
    'cat_id' => '439',
    'cat_name' => '饼干',
    'measure_unit' => '',
    'parent_id' => '370',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 57,
    'level' => 2,
    'id' => '439',
    'name' => '饼干',
  ),
  443 => 
  array (
    'cat_id' => '443',
    'cat_name' => '糕点',
    'measure_unit' => '',
    'parent_id' => '370',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '443',
    'name' => '糕点',
  ),
  442 => 
  array (
    'cat_id' => '442',
    'cat_name' => '蛋卷',
    'measure_unit' => '',
    'parent_id' => '370',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '12',
    'level' => 2,
    'id' => '442',
    'name' => '蛋卷',
  ),
  522 => 
  array (
    'cat_id' => '522',
    'cat_name' => '面包',
    'measure_unit' => '',
    'parent_id' => '370',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 43,
    'level' => 2,
    'id' => '522',
    'name' => '面包',
  ),
  440 => 
  array (
    'cat_id' => '440',
    'cat_name' => '派',
    'measure_unit' => '',
    'parent_id' => '370',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 9,
    'level' => 2,
    'id' => '440',
    'name' => '派',
  ),
  374 => 
  array (
    'cat_id' => '374',
    'cat_name' => '地方特产',
    'measure_unit' => '',
    'parent_id' => '358',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 1,
    'id' => '374',
    'name' => '地方特产',
  ),
  459 => 
  array (
    'cat_id' => '459',
    'cat_name' => '碗团',
    'measure_unit' => '',
    'parent_id' => '374',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '459',
    'name' => '碗团',
  ),
  462 => 
  array (
    'cat_id' => '462',
    'cat_name' => '芝麻饼',
    'measure_unit' => '',
    'parent_id' => '374',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '462',
    'name' => '芝麻饼',
  ),
  460 => 
  array (
    'cat_id' => '460',
    'cat_name' => '枣',
    'measure_unit' => '',
    'parent_id' => '374',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '460',
    'name' => '枣',
  ),
  376 => 
  array (
    'cat_id' => '376',
    'cat_name' => '生鲜水果',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '5',
    'goods_num' => 0,
    'level' => 0,
    'id' => '376',
    'name' => '生鲜水果',
  ),
  378 => 
  array (
    'cat_id' => '378',
    'cat_name' => '生肉',
    'measure_unit' => '',
    'parent_id' => '376',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '378',
    'name' => '生肉',
  ),
  380 => 
  array (
    'cat_id' => '380',
    'cat_name' => '散称熟食',
    'measure_unit' => '',
    'parent_id' => '376',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '380',
    'name' => '散称熟食',
  ),
  498 => 
  array (
    'cat_id' => '498',
    'cat_name' => '蔬菜',
    'measure_unit' => '',
    'parent_id' => '376',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '498',
    'name' => '蔬菜',
  ),
  379 => 
  array (
    'cat_id' => '379',
    'cat_name' => '水产',
    'measure_unit' => '',
    'parent_id' => '376',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '379',
    'name' => '水产',
  ),
  377 => 
  array (
    'cat_id' => '377',
    'cat_name' => '水果',
    'measure_unit' => '',
    'parent_id' => '376',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '377',
    'name' => '水果',
  ),
  372 => 
  array (
    'cat_id' => '372',
    'cat_name' => '饮料酒水',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '7',
    'goods_num' => 0,
    'level' => 0,
    'id' => '372',
    'name' => '饮料酒水',
  ),
  453 => 
  array (
    'cat_id' => '453',
    'cat_name' => '水',
    'measure_unit' => '',
    'parent_id' => '372',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '453',
    'name' => '水',
  ),
  449 => 
  array (
    'cat_id' => '449',
    'cat_name' => '碳酸饮料',
    'measure_unit' => '',
    'parent_id' => '372',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 4,
    'level' => 1,
    'id' => '449',
    'name' => '碳酸饮料',
  ),
  371 => 
  array (
    'cat_id' => '371',
    'cat_name' => '酒类',
    'measure_unit' => '',
    'parent_id' => '372',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '5',
    'goods_num' => 0,
    'level' => 1,
    'id' => '371',
    'name' => '酒类',
  ),
  447 => 
  array (
    'cat_id' => '447',
    'cat_name' => '预调酒',
    'measure_unit' => '',
    'parent_id' => '371',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '447',
    'name' => '预调酒',
  ),
  448 => 
  array (
    'cat_id' => '448',
    'cat_name' => '保健酒',
    'measure_unit' => '',
    'parent_id' => '371',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '448',
    'name' => '保健酒',
  ),
  446 => 
  array (
    'cat_id' => '446',
    'cat_name' => '红酒',
    'measure_unit' => '',
    'parent_id' => '371',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '446',
    'name' => '红酒',
  ),
  445 => 
  array (
    'cat_id' => '445',
    'cat_name' => '白酒',
    'measure_unit' => '',
    'parent_id' => '371',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '445',
    'name' => '白酒',
  ),
  444 => 
  array (
    'cat_id' => '444',
    'cat_name' => '啤酒',
    'measure_unit' => '',
    'parent_id' => '371',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '444',
    'name' => '啤酒',
  ),
  452 => 
  array (
    'cat_id' => '452',
    'cat_name' => '功能饮料',
    'measure_unit' => '',
    'parent_id' => '372',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '452',
    'name' => '功能饮料',
  ),
  450 => 
  array (
    'cat_id' => '450',
    'cat_name' => '茶饮品',
    'measure_unit' => '',
    'parent_id' => '372',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '450',
    'name' => '茶饮品',
  ),
  373 => 
  array (
    'cat_id' => '373',
    'cat_name' => '牛奶乳饮品',
    'measure_unit' => '',
    'parent_id' => '372',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '5',
    'goods_num' => 0,
    'level' => 1,
    'id' => '373',
    'name' => '牛奶乳饮品',
  ),
  457 => 
  array (
    'cat_id' => '457',
    'cat_name' => '常温奶',
    'measure_unit' => '',
    'parent_id' => '373',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '457',
    'name' => '常温奶',
  ),
  454 => 
  array (
    'cat_id' => '454',
    'cat_name' => '乳饮品',
    'measure_unit' => '',
    'parent_id' => '373',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '454',
    'name' => '乳饮品',
  ),
  458 => 
  array (
    'cat_id' => '458',
    'cat_name' => '儿童奶',
    'measure_unit' => '',
    'parent_id' => '373',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '458',
    'name' => '儿童奶',
  ),
  455 => 
  array (
    'cat_id' => '455',
    'cat_name' => '果味奶饮品',
    'measure_unit' => '',
    'parent_id' => '373',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '455',
    'name' => '果味奶饮品',
  ),
  456 => 
  array (
    'cat_id' => '456',
    'cat_name' => '酸奶',
    'measure_unit' => '',
    'parent_id' => '373',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '5',
    'level' => 2,
    'id' => '456',
    'name' => '酸奶',
  ),
  451 => 
  array (
    'cat_id' => '451',
    'cat_name' => '果汁饮品',
    'measure_unit' => '',
    'parent_id' => '372',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '451',
    'name' => '果汁饮品',
  ),
  383 => 
  array (
    'cat_id' => '383',
    'cat_name' => '家居生活',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '9',
    'goods_num' => 0,
    'level' => 0,
    'id' => '383',
    'name' => '家居生活',
  ),
  385 => 
  array (
    'cat_id' => '385',
    'cat_name' => '厨房用具',
    'measure_unit' => '',
    'parent_id' => '383',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '7',
    'goods_num' => 0,
    'level' => 1,
    'id' => '385',
    'name' => '厨房用具',
  ),
  472 => 
  array (
    'cat_id' => '472',
    'cat_name' => '清洁用品',
    'measure_unit' => '',
    'parent_id' => '385',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '472',
    'name' => '清洁用品',
  ),
  469 => 
  array (
    'cat_id' => '469',
    'cat_name' => '陶瓷类',
    'measure_unit' => '',
    'parent_id' => '385',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '469',
    'name' => '陶瓷类',
  ),
  473 => 
  array (
    'cat_id' => '473',
    'cat_name' => '刀具',
    'measure_unit' => '',
    'parent_id' => '385',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '473',
    'name' => '刀具',
  ),
  470 => 
  array (
    'cat_id' => '470',
    'cat_name' => '塑料制品',
    'measure_unit' => '',
    'parent_id' => '385',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '470',
    'name' => '塑料制品',
  ),
  474 => 
  array (
    'cat_id' => '474',
    'cat_name' => '厨房电器',
    'measure_unit' => '',
    'parent_id' => '385',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '474',
    'name' => '厨房电器',
  ),
  471 => 
  array (
    'cat_id' => '471',
    'cat_name' => '餐具',
    'measure_unit' => '',
    'parent_id' => '385',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '471',
    'name' => '餐具',
  ),
  468 => 
  array (
    'cat_id' => '468',
    'cat_name' => '不锈钢厨具',
    'measure_unit' => '',
    'parent_id' => '385',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '468',
    'name' => '不锈钢厨具',
  ),
  514 => 
  array (
    'cat_id' => '514',
    'cat_name' => '卫浴用品',
    'measure_unit' => '',
    'parent_id' => '383',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '514',
    'name' => '卫浴用品',
  ),
  388 => 
  array (
    'cat_id' => '388',
    'cat_name' => '床上用品',
    'measure_unit' => '',
    'parent_id' => '383',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '6',
    'goods_num' => 0,
    'level' => 1,
    'id' => '388',
    'name' => '床上用品',
  ),
  479 => 
  array (
    'cat_id' => '479',
    'cat_name' => '床垫/床褥',
    'measure_unit' => '',
    'parent_id' => '388',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '479',
    'name' => '床垫/床褥',
  ),
  480 => 
  array (
    'cat_id' => '480',
    'cat_name' => '床品套装',
    'measure_unit' => '',
    'parent_id' => '388',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '480',
    'name' => '床品套装',
  ),
  477 => 
  array (
    'cat_id' => '477',
    'cat_name' => '被子/枕头',
    'measure_unit' => '',
    'parent_id' => '388',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '477',
    'name' => '被子/枕头',
  ),
  482 => 
  array (
    'cat_id' => '482',
    'cat_name' => '蚊帐/凉席',
    'measure_unit' => '',
    'parent_id' => '388',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '482',
    'name' => '蚊帐/凉席',
  ),
  478 => 
  array (
    'cat_id' => '478',
    'cat_name' => '床单被罩',
    'measure_unit' => '',
    'parent_id' => '388',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '478',
    'name' => '床单被罩',
  ),
  481 => 
  array (
    'cat_id' => '481',
    'cat_name' => '窗帘/窗纱',
    'measure_unit' => '',
    'parent_id' => '388',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '481',
    'name' => '窗帘/窗纱',
  ),
  518 => 
  array (
    'cat_id' => '518',
    'cat_name' => '日用洗晒',
    'measure_unit' => '',
    'parent_id' => '383',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '518',
    'name' => '日用洗晒',
  ),
  515 => 
  array (
    'cat_id' => '515',
    'cat_name' => '一次性用品',
    'measure_unit' => '',
    'parent_id' => '383',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '515',
    'name' => '一次性用品',
  ),
  394 => 
  array (
    'cat_id' => '394',
    'cat_name' => '年货节庆',
    'measure_unit' => '',
    'parent_id' => '383',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '394',
    'name' => '年货节庆',
  ),
  389 => 
  array (
    'cat_id' => '389',
    'cat_name' => '针织家居',
    'measure_unit' => '',
    'parent_id' => '383',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '6',
    'goods_num' => 0,
    'level' => 1,
    'id' => '389',
    'name' => '针织家居',
  ),
  487 => 
  array (
    'cat_id' => '487',
    'cat_name' => '洗浴用品',
    'measure_unit' => '',
    'parent_id' => '389',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '487',
    'name' => '洗浴用品',
  ),
  485 => 
  array (
    'cat_id' => '485',
    'cat_name' => '睡衣',
    'measure_unit' => '',
    'parent_id' => '389',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '485',
    'name' => '睡衣',
  ),
  486 => 
  array (
    'cat_id' => '486',
    'cat_name' => '毛巾/浴巾',
    'measure_unit' => '',
    'parent_id' => '389',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '486',
    'name' => '毛巾/浴巾',
  ),
  483 => 
  array (
    'cat_id' => '483',
    'cat_name' => '袜子',
    'measure_unit' => '',
    'parent_id' => '389',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '483',
    'name' => '袜子',
  ),
  536 => 
  array (
    'cat_id' => '536',
    'cat_name' => '拖鞋',
    'measure_unit' => '',
    'parent_id' => '389',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
    'level' => 2,
    'id' => '536',
    'name' => '拖鞋',
  ),
  484 => 
  array (
    'cat_id' => '484',
    'cat_name' => '内衣',
    'measure_unit' => '',
    'parent_id' => '389',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '484',
    'name' => '内衣',
  ),
  517 => 
  array (
    'cat_id' => '517',
    'cat_name' => '箱包饰品',
    'measure_unit' => '',
    'parent_id' => '383',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '517',
    'name' => '箱包饰品',
  ),
  516 => 
  array (
    'cat_id' => '516',
    'cat_name' => '整理收纳',
    'measure_unit' => '',
    'parent_id' => '383',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '516',
    'name' => '整理收纳',
  ),
  359 => 
  array (
    'cat_id' => '359',
    'cat_name' => '粮油副食',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '7',
    'goods_num' => 0,
    'level' => 0,
    'id' => '359',
    'name' => '粮油副食',
  ),
  397 => 
  array (
    'cat_id' => '397',
    'cat_name' => '散称杂粮',
    'measure_unit' => '',
    'parent_id' => '359',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '397',
    'name' => '散称杂粮',
  ),
  509 => 
  array (
    'cat_id' => '509',
    'cat_name' => '菌菇干货',
    'measure_unit' => '',
    'parent_id' => '359',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '509',
    'name' => '菌菇干货',
  ),
  395 => 
  array (
    'cat_id' => '395',
    'cat_name' => '食用油',
    'measure_unit' => '',
    'parent_id' => '359',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '395',
    'name' => '食用油',
  ),
  510 => 
  array (
    'cat_id' => '510',
    'cat_name' => '下饭菜',
    'measure_unit' => '',
    'parent_id' => '359',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 1,
    'id' => '510',
    'name' => '下饭菜',
  ),
  437 => 
  array (
    'cat_id' => '437',
    'cat_name' => '酱菜',
    'measure_unit' => '',
    'parent_id' => '510',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '437',
    'name' => '酱菜',
  ),
  507 => 
  array (
    'cat_id' => '507',
    'cat_name' => '大米面粉',
    'measure_unit' => '',
    'parent_id' => '359',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '507',
    'name' => '大米面粉',
  ),
  511 => 
  array (
    'cat_id' => '511',
    'cat_name' => '调味酱',
    'measure_unit' => '',
    'parent_id' => '359',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '511',
    'name' => '调味酱',
  ),
  508 => 
  array (
    'cat_id' => '508',
    'cat_name' => '厨房调味',
    'measure_unit' => '',
    'parent_id' => '359',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '7',
    'goods_num' => 0,
    'level' => 1,
    'id' => '508',
    'name' => '厨房调味',
  ),
  533 => 
  array (
    'cat_id' => '533',
    'cat_name' => '糖',
    'measure_unit' => '',
    'parent_id' => '508',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '533',
    'name' => '糖',
  ),
  534 => 
  array (
    'cat_id' => '534',
    'cat_name' => '芝麻油',
    'measure_unit' => '',
    'parent_id' => '508',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '534',
    'name' => '芝麻油',
  ),
  404 => 
  array (
    'cat_id' => '404',
    'cat_name' => '香料',
    'measure_unit' => '',
    'parent_id' => '508',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '404',
    'name' => '香料',
  ),
  399 => 
  array (
    'cat_id' => '399',
    'cat_name' => '醋',
    'measure_unit' => '',
    'parent_id' => '508',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '399',
    'name' => '醋',
  ),
  535 => 
  array (
    'cat_id' => '535',
    'cat_name' => '料酒',
    'measure_unit' => '',
    'parent_id' => '508',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '535',
    'name' => '料酒',
  ),
  403 => 
  array (
    'cat_id' => '403',
    'cat_name' => '调味料',
    'measure_unit' => '',
    'parent_id' => '508',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '403',
    'name' => '调味料',
  ),
  532 => 
  array (
    'cat_id' => '532',
    'cat_name' => '酱油',
    'measure_unit' => '',
    'parent_id' => '508',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '532',
    'name' => '酱油',
  ),
  390 => 
  array (
    'cat_id' => '390',
    'cat_name' => '美容洗护',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '6',
    'goods_num' => 0,
    'level' => 0,
    'id' => '390',
    'name' => '美容洗护',
  ),
  491 => 
  array (
    'cat_id' => '491',
    'cat_name' => '口腔护理',
    'measure_unit' => '',
    'parent_id' => '390',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
    'level' => 1,
    'id' => '491',
    'name' => '口腔护理',
  ),
  513 => 
  array (
    'cat_id' => '513',
    'cat_name' => '男性护理',
    'measure_unit' => '',
    'parent_id' => '390',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '513',
    'name' => '男性护理',
  ),
  512 => 
  array (
    'cat_id' => '512',
    'cat_name' => '精致彩妆',
    'measure_unit' => '',
    'parent_id' => '390',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '512',
    'name' => '精致彩妆',
  ),
  490 => 
  array (
    'cat_id' => '490',
    'cat_name' => '护肤品',
    'measure_unit' => '',
    'parent_id' => '390',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '490',
    'name' => '护肤品',
  ),
  493 => 
  array (
    'cat_id' => '493',
    'cat_name' => '女性护理',
    'measure_unit' => '',
    'parent_id' => '390',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '5',
    'level' => 1,
    'id' => '493',
    'name' => '女性护理',
  ),
  488 => 
  array (
    'cat_id' => '488',
    'cat_name' => '个人洗护',
    'measure_unit' => '',
    'parent_id' => '390',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '488',
    'name' => '个人洗护',
  ),
  384 => 
  array (
    'cat_id' => '384',
    'cat_name' => '文体玩具',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '5',
    'goods_num' => 0,
    'level' => 0,
    'id' => '384',
    'name' => '文体玩具',
  ),
  464 => 
  array (
    'cat_id' => '464',
    'cat_name' => '办公用品',
    'measure_unit' => '',
    'parent_id' => '384',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '464',
    'name' => '办公用品',
  ),
  466 => 
  array (
    'cat_id' => '466',
    'cat_name' => '礼品',
    'measure_unit' => '',
    'parent_id' => '384',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '466',
    'name' => '礼品',
  ),
  467 => 
  array (
    'cat_id' => '467',
    'cat_name' => '棋牌扑克',
    'measure_unit' => '',
    'parent_id' => '384',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '467',
    'name' => '棋牌扑克',
  ),
  465 => 
  array (
    'cat_id' => '465',
    'cat_name' => '玩具',
    'measure_unit' => '',
    'parent_id' => '384',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '465',
    'name' => '玩具',
  ),
  463 => 
  array (
    'cat_id' => '463',
    'cat_name' => '体育用品',
    'measure_unit' => '',
    'parent_id' => '384',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '463',
    'name' => '体育用品',
  ),
  386 => 
  array (
    'cat_id' => '386',
    'cat_name' => '家用小家电',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 0,
    'id' => '386',
    'name' => '家用小家电',
  ),
  476 => 
  array (
    'cat_id' => '476',
    'cat_name' => '小家电',
    'measure_unit' => '',
    'parent_id' => '386',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '476',
    'name' => '小家电',
  ),
  475 => 
  array (
    'cat_id' => '475',
    'cat_name' => '插座',
    'measure_unit' => '',
    'parent_id' => '386',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '475',
    'name' => '插座',
  ),
  499 => 
  array (
    'cat_id' => '499',
    'cat_name' => '家庭清洁',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '8',
    'goods_num' => 0,
    'level' => 0,
    'id' => '499',
    'name' => '家庭清洁',
  ),
  504 => 
  array (
    'cat_id' => '504',
    'cat_name' => '驱蚊驱虫',
    'measure_unit' => '',
    'parent_id' => '499',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '504',
    'name' => '驱蚊驱虫',
  ),
  502 => 
  array (
    'cat_id' => '502',
    'cat_name' => '卫生间清洁',
    'measure_unit' => '',
    'parent_id' => '499',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '502',
    'name' => '卫生间清洁',
  ),
  503 => 
  array (
    'cat_id' => '503',
    'cat_name' => '清洁工具',
    'measure_unit' => '',
    'parent_id' => '499',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '503',
    'name' => '清洁工具',
  ),
  505 => 
  array (
    'cat_id' => '505',
    'cat_name' => '家私清洁',
    'measure_unit' => '',
    'parent_id' => '499',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '505',
    'name' => '家私清洁',
  ),
  501 => 
  array (
    'cat_id' => '501',
    'cat_name' => '厨房清洁',
    'measure_unit' => '',
    'parent_id' => '499',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '501',
    'name' => '厨房清洁',
  ),
  506 => 
  array (
    'cat_id' => '506',
    'cat_name' => '客厅清洁',
    'measure_unit' => '',
    'parent_id' => '499',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '506',
    'name' => '客厅清洁',
  ),
  500 => 
  array (
    'cat_id' => '500',
    'cat_name' => '衣物清洁',
    'measure_unit' => '',
    'parent_id' => '499',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '500',
    'name' => '衣物清洁',
  ),
  391 => 
  array (
    'cat_id' => '391',
    'cat_name' => '纸制品',
    'measure_unit' => '',
    'parent_id' => '499',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
    'level' => 1,
    'id' => '391',
    'name' => '纸制品',
  ),
);
?>